### ISSUE TITLE
Change isFindQuery to isFind

### ISSUE THREAD

**Issue by mananjadhav** [ackerdev/objection-softdelete#3]
I guess with the latest version of objectionjs isFindQuery is deprecated and has to be replaced with isFind.

Due to this, for some reasons in my query I could see multiple `deleted_at is null`

Attached is the reference image. If I change the function, everything works okay.

![Ref Screenshot](https://user-images.githubusercontent.com/3069065/43480063-c2efd056-951f-11e8-80a2-134d46c973db.png)

**Comment by mananjadhav** [comment]
And by the way, based on the depth of the query, number of deleted_at keep adding up. 

Please check the screenshot below:

![screen shot 2018-08-01 at 1 34 14 am](https://user-images.githubusercontent.com/3069065/43484114-0de5202e-952b-11e8-8675-d1326916791c.png)

**Comment by ackerdev** [comment]
`isFindQuery` -> `isFind` has already been fixed in #1 and was released as of v2.0.0 of this package, so be sure to upgrade.

As for the `deleted_at` issue, I recommend submitting a PR if you are able. I'm not working on this project actively, but would be more than happy to merge in a PR and publish a new version to npm.

**Comment by mananjadhav** [comment]
Thanks for the response. Will sure try to upgrade.  Didn't check the version 2.

If I am able to fix deleted_at I'll submit the PR. :)
